#####   NOT WORKING due to AgentMemory class being mysterious   #####

import os
import math
from typing import Optional, Tuple
from dotenv import load_dotenv, find_dotenv
from PIL import Image
from smolagents import tool, CodeAgent, DuckDuckGoSearchTool, FinalAnswerTool, AzureOpenAIServerModel, HfApiModel, VisitWebpageTool #, GoogleSearchTool
from smolagents.utils import encode_image_base64, make_image_url

from dotenv import load_dotenv, find_dotenv


@tool
def calculate_cargo_travel_time(
    origin_coords: Tuple[float, float],
    destination_coords: Tuple[float, float],
    cruising_speed_kmh: Optional[float] = 750.0,  # Average speed for cargo planes
) -> float:
    """
    Calculate the travel time for a cargo plane between two points on Earth using great-circle distance.

    Args:
        origin_coords: Tuple of (latitude, longitude) for the starting point
        destination_coords: Tuple of (latitude, longitude) for the destination
        cruising_speed_kmh: Optional cruising speed in km/h (defaults to 750 km/h for typical cargo planes)

    Returns:
        float: The estimated travel time in hours

    Example:
        >>> # Chicago (41.8781° N, 87.6298° W) to Sydney (33.8688° S, 151.2093° E)
        >>> result = calculate_cargo_travel_time((41.8781, -87.6298), (-33.8688, 151.2093))
    """

    def to_radians(degrees: float) -> float:
        return degrees * (math.pi / 180)

    # Extract coordinates
    lat1, lon1 = map(to_radians, origin_coords)
    lat2, lon2 = map(to_radians, destination_coords)

    # Earth's radius in kilometers
    EARTH_RADIUS_KM = 6371.0

    # Calculate great-circle distance using the haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = (
        math.sin(dlat / 2) ** 2
        + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    )
    c = 2 * math.asin(math.sqrt(a))
    distance = EARTH_RADIUS_KM * c

    # Add 10% to account for non-direct routes and air traffic controls
    actual_distance = distance * 1.1

    # Calculate flight time
    # Add 1 hour for takeoff and landing procedures
    flight_time = (actual_distance / cruising_speed_kmh) + 1.0

    # Format the results
    return round(flight_time, 2)


@tool
def check_reasoning_and_plot(final_answer, agent_memory):
    """ 
    Validate the reasoning process and plot generated by an agent against a user-given task.

    Args:
        final_answer: The final answer provided by the agent.
        agent_memory: An object containing the agent's memory, including the steps taken to reach the final answer.

    Returns:
        bool: Returns True if the plot and reasoning process pass the validation, otherwise raises an Exception.

    Example:
        >>> # Assuming agent_memory is an object with the necessary methods
        >>> result = check_reasoning_and_plot("final answer", agent_memory)
    """
    multimodal_model = AzureOpenAIServerModel(
        model_id=os.getenv("AZURE_OPENAI_MODEL"),
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        api_version=os.getenv("OPENAI_API_VERSION"),
        max_tokens=8000
    )
    filepath = "./tmp/saved_map.png"
    assert os.path.exists(filepath), "Make sure to save the plot under saved_map.png!"
    image = Image.open(filepath)
    prompt = (
        f"""Here is a user-given task and the agent steps: {agent_memory.get_succinct_steps()}. Now here is the plot that was made.
        Please check that the reasoning process and plot are correct: do they correctly answer the given task?
        First list reasons why yes/no, then write your final decision: PASS in caps lock if it is satisfactory, FAIL if it is not.
        Don't be harsh: if the plot mostly solves the task, it should pass.
        To pass, a plot should be made using px.scatter_map and not any other method (scatter_map looks nicer)."""
    )
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": prompt,
                },
                {
                    "type": "image_url",
                    "image_url": {"url": make_image_url(encode_image_base64(image))},
                },
            ],
        }
    ]
    output = multimodal_model(messages).content
    print("Feedback: ", output)
    if "FAIL" in output:
        raise Exception(output)
    return True


model = AzureOpenAIServerModel(
    model_id=os.getenv("AZURE_OPENAI_MODEL"),
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("OPENAI_API_VERSION"),
    max_tokens=8000
)


web_agent = CodeAgent(
    model=model,
    tools=[DuckDuckGoSearchTool(), VisitWebpageTool(), calculate_cargo_travel_time], # GoogleSearchTool("serper")
    name="web_agent",
    description="Browses the web to find information",
    additional_authorized_imports=["pandas"],
    verbosity_level=0,
    max_steps=10,
)


manager_agent = CodeAgent(
    model=HfApiModel("deepseek-ai/DeepSeek-R1", provider="together", max_tokens=8096),
    tools=[calculate_cargo_travel_time],
    managed_agents=[web_agent],
    additional_authorized_imports=["geopandas", "plotly", "shapely", "json", "pandas", "numpy"],
    planning_interval=5,
    verbosity_level=2,
    final_answer_checks=[check_reasoning_and_plot],
    max_steps=15,
)


if os.getenv('ENV') == 'local':
    message = input('Ask something to your agent: ')
    # agent.run("Find all Batman filming locations in the world, calculate the time to transfer via cargo plane to here (we're in Gotham, 40.7128° N, 74.0060° W), and return them to me as a pandas dataframe. Also give me some supercar factories with the same cargo plane transfer time.")
    manager_agent.visualize()
    # result = manager_agent.run(message)
    # result